{% set name = "idr-py" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e355a7636e5f6883d19955dd3d3edfc4de263040796fad593f4676e49e8a413c

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python
  run:
    - python
    - omero-py
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - requests
    - seaborn

test:
  imports:
    - idr
    - idr.attributes
    - idr.connections
    - idr.externalDBs
    - idr.images
    - idr.visualizations
    - idr.widgets

about:
  home: https://idr.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Library with helper methods for accessing the Image Data Resource (IDR).
  doc_url: https://idr.openmicroscopy.org/about/api.html
  dev_url: https://github.com/IDR/idr-py

extra:
  recipe-maintainers:
    - ome
